adapter: "mysql"
database: "1050"
host: "localhost"
port: 3306
username: "root"
password: "123321"
encoding: "utf8"

# adapter: "mysql"
# database: "1050"
# host: "127.4.79.130"
# port: 3306
# username: "adminF469Nqg"
# password: "nJWaDzrgnywB"
# encoding: "utf8"